project_root_path : /Users/cloud.chen/code/taifex-fdms-cms
old_project_root_path : /Users/cloud.chen/code/taifex-fdms-old/FMS
repository_path : /src/main/java/com/mitake/infra/repository
service_directory_path : /src/main/java/com/mitake/infra/repository/app/service
serviceimpl_directory_path : /src/main/java/com/mitake/infra/repository/app/service/impl
controller_directory_path : /src/main/java/com/mitake/controller
dao_directory_path : /src/main/java/com/mitake/infra/repository/app/dao
sql_directory_path : /db/phase-1-data.sql
jsp_directory_path : /src/main/webapp/WEB-INF/jsp/
js_directory_path : /src/main/resources/static/js/
csv_file_path : ./function_number.csv
log_path : ./log.txt
ignore_file_path_list : 
  - FuturesHelper.java
  - NativeQueryDao.java
  - NativeQueryDao2.java
  - FuturesDao.java
  - Fi41Dao.java 
independent_file_rules :
  - CommentRule :
    - code_comment_should_not_exist
    - todo_comment_generated_by_system_should_not_exist
  - AnnotationRule :
    - method_should_add_transaction_annotation
  - GenericTypeRule :
    - should_not_using_generic_type
  - MethodNameRule :
    - method_name_defination_initial_should_not_be_capital
    - method_name_initial_should_not_be_capital
    - method_should_using_restricted_name
  - LegacyDirectoryPathRule :
    - legacy_file_name_and_path_should_be_same_as_old_project